# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
env:
  - JULIA_NUM_THREADS=1
  - JULIA_NUM_THREADS=4

notifications:
  email: false

matrix:
 allow_failures:
 - julia: nightly

codecov: true
coveralls: true
